version: "3"
services:
  mariadb:
    image: mariadb:10.4
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
      MYSQL_DATABASE: survey
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - mariadb
  flyway:
    image: flyway/flyway:7.3
    command: -url=jdbc:mariadb://mariadb:3306/survey -user=root -password=mysecret -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - mariadb
